// stage 0
const circle = ["Circle","Can be Caught\nBear+Any\nSun+Any"]
const ellipse = ["Ellipse","Can be Caught\nBean+Any"]
const soap = ["Soap","Can be Caught\nCircle+Square\nLemon+Any"]
const square = ["Square","Can be Caught\nConcave+Any\nConvex+Any"]
const triangle = ["Triangle","Can be Caught\nDreidel+Any"]
const balloon = ["Balloon","Can be Caught\nKagami Mochi+Any\nRaindrop+Any\nRocket+Any"]

// stage 1
const bear = ["Bear","Circle+Circle"]
const onion = ["Onion","Circle+Circle"]
const slime = ["Slime","Circle+Circle"]
const whip = ["Whip","Circle+Circle"]
const bean = ["Bean","Circle+Ellipse"]
const onigiri = ["Onigiri","Circle+Triangle\nMozart+Any"]
const kagamimochi = ["Kagami Mochi","Balloon+Balloon"]
const rocket = ["Rocket","Balloon+Balloon"]
const ship = ["Ship","Balloon+Balloon\nKagami Mochi+Kagami Mochi\nTower+Any"]
const candy = ["Candy","Ellipse+Ellipse"]
const headphones = ["Headphones","Ellipse+Ellipse\nSoap+Soap\nThorns+Any\nDevil+Any"]
const lemon = ["Lemon","Ellipse+Ellipse\nSoap+Soap"]
const thorns = ["Thorns","Ellipse+Ellipse\nSoap+Soap"]
const concave = ["Concave","Square+Square"]
const convex = ["Convex","Square+Square\nConcave+Concave"]
const buildingbrick = ["Building Brick","Square+Square\nConvex+Convex"]
const sparkle = ["Sparkle","Triangle+Triangle"]
const dreidel = ["Dreidel","Triangle+Triangle\nOnigiri+Onigiri"]

// stage 2
const crescent = ["Crescent","Bean+Bean\nBean+Dreidel\nBean+Devil"];
const cat = ["Cat","Bear+Bear\nSheep+Any"]
const jester = ["Jester","Bear+Bear"]
const mouse = ["Mouse","Bear+Bear\nJester+Any"]
const sheep = ["Sheep","Bear+Bear"]
const fishbowl = ["Fishbowl","Concave+Concave\nKagami Mochi+Ship\nRocket+Rocket"]
const tower = ["Tower","Concave+Convex\nBuilding Brick + Building Brick"]
const mozart = ["Mozart","Headphones+Onigiri"]
const devil = ["Devil","Headphones+Thorns"]
const dog = ["Dog","Onigiri+Onigiri"]
const meteor = ["Meteor","Slime+Slime\nOnion+Onion\nWhip+Whip"]
const pot = ["Pot","Slime+Slime\nOnion+Onion"]
const tripeaks = ["Tri-Peaks","Slime+Slime\nOnion+Onion\nWhip+Whip"]
const waves = ["Waves","Slime+Slime\nOnion+Onion\nWhip+Whip"]
